name: 8278 Bowman Woods
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5269202184863389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aab3ae'
    - '#000004'
    - '#fefefe'
    - '#525460'
    - '#9e4c4e'
  brandStrength: 0.3666510512121022
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
